#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2_Python"
else
    POSH_DIR="${POSHC2_DIR}" 
fi

# Create and edit config if doesn't exist
if [[ ! -f "$POSH_DIR/project/Config.py" ]]; then
    mkdir -p "$POSH_DIR/project" > /dev/null 2>&1
    cp "$POSH_DIR/Config.py" "$POSH_DIR/project/Config.py" > /dev/null 2>&1
    echo "No Config.py was found for this project, one has been created in the project folder, please edit it and relaunch"
else
    posh-server
fi
