#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
    project_folder="/opt/PoshC2_Python/project"
else
    project_folder="${POSHC2_DIR}/project"
fi

if [[ ! -d "$project_folder" ]]; then
    mkdir -p "$project_folder" > /dev/null 2>&1
fi

port=$(cat $project_folder/Config.py | grep "PORT_NUMBER" | cut -d " " -f 3)

sudo docker run -ti --rm -p "$port":443 -v "$project_folder:/opt/PoshC2_Python/project" nettitude/poshc2 /usr/bin/posh-docker-entrypoint
