#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2_Python"
else
    POSH_DIR="${POSHC2_DIR}" 
fi

sudo docker run -ti --rm -v "$POSH_DIR/project:/opt/PoshC2_Python/project" nettitude/poshc2 /usr/bin/posh "$@"
