#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2_Python"
else
    POSH_DIR="${POSHC2_DIR}" 
fi

# Create and edit config if doesn't exist
if [[ ! -f "$POSH_DIR/project/Config.py" ]]; then
    mkdir -p "$POSH_DIR/project" > /dev/null 2>&1
    cp "$POSH_DIR/Config.py" "$POSH_DIR/project/Config.py" > /dev/null 2>&1
    sed -i "s/### DO NOT.*$//g" "$POSH_DIR/project/Config.py"
    echo "No Config.py was found for this project, one has been created in the project folder, please edit it and relaunch"
else
    port=$(cat "$POSH_DIR/project/Config.py" | grep "PORT_NUMBER" | cut -d " " -f 3)

    sudo docker run -ti --rm -p "$port":443 -v "$POSH_DIR/project:/opt/PoshC2_Python/project" nettitude/poshc2 /usr/bin/posh-server
fi
